### ISSUE TITLE
Improve inline code documentation

### ISSUE THREAD

**Issue by drkennetz** [drkennetz/slackgpt#33]
## Description

I don't think all the code is documented well enough

## Reason

It should be documented

## Proposed Changes

write function and package level docs

## Additional Information

-

## Impact

The program will be easier to understand

## Reviewers

-

**Comment by hemantsoni42** [comment]
@drkennetz can you please assign me this code? And also can please provide me names of files you want to add inline code documentation. According to me main.go is the only file that require inline code documentation.

**Comment by drkennetz** [comment]
@hemantsoni42 I've completed this, and am putting this on pause for the time being. Thanks for all your help on the project.
